In [62]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import swish
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import math

In [63]:
df = pd.read_csv("/content/Housing.csv")
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:
category_mappings = {}
def convert_to_int(column):
    if column.dtype == 'object':
        unique_vals = column.unique()
        val_map = {val: idx for idx, val in enumerate(unique_vals)}
        category_mappings[column.name] = val_map
        return column.map(val_map)
    return column

df = df.apply(convert_to_int)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,0,0,0,0,0,2,0,0
1,12250000,8960,4,4,4,0,0,0,0,0,3,1,0
2,12250000,9960,3,2,2,0,0,1,0,1,2,0,1
3,12215000,7500,4,2,2,0,0,1,0,0,3,0,0
4,11410000,7420,4,1,2,0,1,1,0,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,0,0,1,0,1,2,1,2
541,1767150,2400,3,1,1,1,0,0,0,1,0,1,1
542,1750000,3620,2,1,1,0,0,0,0,1,0,1,2
543,1750000,2910,3,1,1,1,0,0,0,1,0,1,0
544,1750000,3850,3,1,2,0,0,0,0,1,0,1,2

In [66]:
X = df.drop(columns=['price'])
y = df['price']

In [67]:
scaler = StandardScaler()
numerical_features = X_train.select_dtypes(include=np.number).columns
X_train_scaled = scaler.fit_transform(X_train[numerical_features])
X_test_scaled = scaler.transform(X_test[numerical_features])

In [68]:
X_train = pd.DataFrame(X_train_scaled, index=X_train.index, columns=numerical_features)
X_test = pd.DataFrame(X_test_scaled, index=X_test.index, columns=numerical_features)

X_train = pd.concat([X_train, X_train.select_dtypes(exclude=np.number)], axis=1)
X_test = pd.concat([X_test, X_test.select_dtypes(exclude=np.number)], axis=1)

In [69]:
# Build ANN model
model = Sequential([
    Dense(18, activation=swish, input_shape=(X_train.shape[1],)),
    Dense(26, activation=swish),
    Dense(20, activation=swish),
    Dense(15, activation=swish),
    Dense(1, activation='linear')
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [70]:
model.compile(optimizer='rmsprop', loss='mse')

In [71]:
history = model.fit(X_train, y_train, epochs=200, batch_size=64, validation_data=(X_test, y_test))
model.save("housing_price_model.h5")
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

Epoch 1/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 24417593720832.0000 - val_loss: 30129992499200.0000
Epoch 2/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26530474360832.0000 - val_loss: 30129988304896.0000
Epoch 3/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26565744263168.0000 - val_loss: 30129988304896.0000
Epoch 4/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24577996488704.0000 - val_loss: 30129982013440.0000
Epoch 5/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24680064876544.0000 - val_loss: 30129977819136.0000
Epoch 6/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25306396098560.0000 - val_loss: 30129963139072.0000
Epoch 7/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26350790377472.0000 - val_loss: 30129954750464.0000
Epoch 8/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25636718510080.0000 - val_loss: 30129940070400.0000
Epoch 9/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24899796074496.0000 - val_loss: 30129917001728.0000
Epoch 10/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25165832388608.0000 - val_loss: 30129887641600.0000
Epoch 11/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25832309391360.0000 - val_loss: 30129854087168.0000
Epoch 12/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 26300821536768.0000 - val_loss: 30129812144128.0000
Epoch 13/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24714835656704.0000 - val_loss: 30129757618176.0000
Epoch 14/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25830535200768.0000 - val_loss: 30129694703616.0000
Epoch 15/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24761333710848.0000 - val_loss: 30129623400448.0000
Epoch 16/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24161948794880.0000 - val_loss: 30129535320064.0000
Epoch 17/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24645447188480.0000 - val_loss: 30129434656768.0000
Epoch 18/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24838557138944.0000 - val_loss: 30129319313408.0000
Epoch 19/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24927155519488.0000 - val_loss: 30129185095680.0000
Epoch 20/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25161153642496.0000 - val_loss: 30129036197888.0000
Epoch 21/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26551957585920.0000 - val_loss: 30128860037120.0000
Epoch 22/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26077846044672.0000 - val_loss: 30128662904832.0000
Epoch 23/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25617508597760.0000 - val_loss: 30128442703872.0000
Epoch 24/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 24942947074048.0000 - val_loss: 30128193142784.0000
Epoch 25/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25598860722176.0000 - val_loss: 30127910027264.0000
Epoch 26/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 24218848722944.0000 - val_loss: 30127599648768.0000
Epoch 27/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 25044759609344.0000 - val_loss: 30127245230080.0000
Epoch 28/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26112484704256.0000 - val_loss: 30126865645568.0000
Epoch 29/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 25416861483008.0000 - val_loss: 30126431535104.0000
Epoch 30/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 24600587010048.0000 - val_loss: 30125949190144.0000
Epoch 31/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25208727535616.0000 - val_loss: 30125437485056.0000
Epoch 32/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25790234230784.0000 - val_loss: 30124875448320.0000
Epoch 33/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25856370016256.0000 - val_loss: 30124252594176.0000
Epoch 34/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25143220895744.0000 - val_loss: 30123566825472.0000
Epoch 35/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26021740937216.0000 - val_loss: 30122832822272.0000
Epoch 36/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25318612008960.0000 - val_loss: 30122021224448.0000
Epoch 37/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23949228376064.0000 - val_loss: 30121138323456.0000
Epoch 38/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25853886988288.0000 - val_loss: 30120196702208.0000
Epoch 39/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24539371143168.0000 - val_loss: 30119158611968.0000
Epoch 40/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26814065934336.0000 - val_loss: 30118068092928.0000
Epoch 41/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26394104954880.0000 - val_loss: 30116887396352.0000
Epoch 42/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24501725167616.0000 - val_loss: 30115591356416.0000
Epoch 43/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26026545512448.0000 - val_loss: 30114249179136.0000
Epoch 44/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25215100780544.0000 - val_loss: 30112760201216.0000
Epoch 45/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25838122696704.0000 - val_loss: 30111176851456.0000
Epoch 46/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26352514236416.0000 - val_loss: 30109478158336.0000
Epoch 47/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23929196380160.0000 - val_loss: 30107620081664.0000
Epoch 48/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 25233197105152.0000 - val_loss: 30105669730304.0000
Epoch 49/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 25204692615168.0000 - val_loss: 30103578869760.0000
Epoch 50/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25163942854656.0000 - val_loss: 30101383151616.0000
Epoch 51/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26599697154048.0000 - val_loss: 30099046924288.0000
Epoch 52/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26113038352384.0000 - val_loss: 30096534536192.0000
Epoch 53/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23432907456512.0000 - val_loss: 30093860667392.0000
Epoch 54/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25586885984256.0000 - val_loss: 30091016929280.0000
Epoch 55/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24388254564352.0000 - val_loss: 30088030584832.0000
Epoch 56/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24485541445632.0000 - val_loss: 30084817747968.0000
Epoch 57/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24604053602304.0000 - val_loss: 30081468596224.0000
Epoch 58/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24967458586624.0000 - val_loss: 30077905534976.0000
Epoch 59/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25232947544064.0000 - val_loss: 30074134855680.0000
Epoch 60/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26456136613888.0000 - val_loss: 30070143975424.0000
Epoch 61/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25647808249856.0000 - val_loss: 30065934991360.0000
Epoch 62/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25723062452224.0000 - val_loss: 30061510000640.0000
Epoch 63/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25677866729472.0000 - val_loss: 30056816574464.0000
Epoch 64/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24789500559360.0000 - val_loss: 30051858907136.0000
Epoch 65/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 24536865046528.0000 - val_loss: 30046634901504.0000
Epoch 66/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24800407846912.0000 - val_loss: 30041121488896.0000
Epoch 67/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25133657882624.0000 - val_loss: 30035519995904.0000
Epoch 68/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25925865439232.0000 - val_loss: 30029566181376.0000
Epoch 69/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25736492613632.0000 - val_loss: 30023249559552.0000
Epoch 70/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24743812005888.0000 - val_loss: 30016605782016.0000
Epoch 71/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24889457115136.0000 - val_loss: 30009685180416.0000
Epoch 72/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25297544019968.0000 - val_loss: 30002326274048.0000
Epoch 73/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25551930654720.0000 - val_loss: 29994761846784.0000
Epoch 74/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25811306414080.0000 - val_loss: 29986914304000.0000
Epoch 75/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24354104541184.0000 - val_loss: 29978466975744.0000
Epoch 76/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25494131048448.0000 - val_loss: 29969828806656.0000
Epoch 77/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25459213467648.0000 - val_loss: 29960773304320.0000
Epoch 78/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24493326073856.0000 - val_loss: 29951147376640.0000
Epoch 79/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25226461052928.0000 - val_loss: 29941236236288.0000
Epoch 80/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23773340237824.0000 - val_loss: 29930706436096.0000
Epoch 81/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24993951907840.0000 - val_loss: 29920084361216.0000
Epoch 82/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26059445633024.0000 - val_loss: 29909003010048.0000
Epoch 83/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25170039275520.0000 - val_loss: 29897198141440.0000
Epoch 84/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25996801605632.0000 - val_loss: 29885248569344.0000
Epoch 85/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24689694998528.0000 - val_loss: 29872472719360.0000
Epoch 86/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24570201374720.0000 - val_loss: 29859277438976.0000
Epoch 87/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24657621155840.0000 - val_loss: 29845505441792.0000
Epoch 88/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25921434157056.0000 - val_loss: 29831498563584.0000
Epoch 89/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24043835097088.0000 - val_loss: 29816275337216.0000
Epoch 90/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24547508092928.0000 - val_loss: 29800871755776.0000
Epoch 91/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24725426274304.0000 - val_loss: 29784815960064.0000
Epoch 92/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24867384590336.0000 - val_loss: 29768235876352.0000
Epoch 93/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25248449691648.0000 - val_loss: 29751095853056.0000
Epoch 94/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23506892881920.0000 - val_loss: 29733022597120.0000
Epoch 95/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25957985419264.0000 - val_loss: 29714733334528.0000
Epoch 96/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24728446173184.0000 - val_loss: 29695330484224.0000
Epoch 97/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24628244250624.0000 - val_loss: 29675313168384.0000
Epoch 98/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24295287816192.0000 - val_loss: 29654660415488.0000
Epoch 99/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24391576453120.0000 - val_loss: 29633298825216.0000
Epoch 100/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23203665674240.0000 - val_loss: 29610760732672.0000
Epoch 101/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24530785402880.0000 - val_loss: 29587891290112.0000
Epoch 102/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25748498808832.0000 - val_loss: 29564973613056.0000
Epoch 103/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24630920216576.0000 - val_loss: 29540751507456.0000
Epoch 104/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24719711535104.0000 - val_loss: 29515648598016.0000
Epoch 105/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24975545204736.0000 - val_loss: 29489369186304.0000
Epoch 106/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24353154531328.0000 - val_loss: 29461982478336.0000
Epoch 107/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24663619010560.0000 - val_loss: 29433750618112.0000
Epoch 108/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26231382736896.0000 - val_loss: 29405193699328.0000
Epoch 109/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24916088848384.0000 - val_loss: 29375122636800.0000
Epoch 110/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23689615638528.0000 - val_loss: 29343680036864.0000
Epoch 111/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25470043160576.0000 - val_loss: 29312640090112.0000
Epoch 112/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24378494418944.0000 - val_loss: 29279794495488.0000
Epoch 113/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24322619998208.0000 - val_loss: 29246005182464.0000
Epoch 114/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25231689252864.0000 - val_loss: 29211116961792.0000
Epoch 115/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23789828046848.0000 - val_loss: 29175180165120.0000
Epoch 116/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 23451872002048.0000 - val_loss: 29137504829440.0000
Epoch 117/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 25537131053056.0000 - val_loss: 29100146163712.0000
Epoch 118/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 23671936647168.0000 - val_loss: 29060723900416.0000
Epoch 119/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 23267188408320.0000 - val_loss: 29020242575360.0000
Epoch 120/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23542131326976.0000 - val_loss: 28978515542016.0000
Epoch 121/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25184182468608.0000 - val_loss: 28936293580800.0000
Epoch 122/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24251151155200.0000 - val_loss: 28893041917952.0000
Epoch 123/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23407974416384.0000 - val_loss: 28847659548672.0000
Epoch 124/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24868875665408.0000 - val_loss: 28801950023680.0000
Epoch 125/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24384462913536.0000 - val_loss: 28753900077056.0000
Epoch 126/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23740555460608.0000 - val_loss: 28704591839232.0000
Epoch 127/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 24186521124864.0000 - val_loss: 28654509752320.0000
Epoch 128/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23651913039872.0000 - val_loss: 28602106118144.0000
Epoch 129/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23728029171712.0000 - val_loss: 28548307877888.0000
Epoch 130/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23650942058496.0000 - val_loss: 28493739982848.0000
Epoch 131/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23044537974784.0000 - val_loss: 28437018312704.0000
Epoch 132/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24213838626816.0000 - val_loss: 28379661205504.0000
Epoch 133/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24539031404544.0000 - val_loss: 28320433438720.0000
Epoch 134/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23272435482624.0000 - val_loss: 28259555213312.0000
Epoch 135/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 23969891614720.0000 - val_loss: 28197603246080.0000
Epoch 136/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23924670726144.0000 - val_loss: 28133860311040.0000
Epoch 137/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23807282642944.0000 - val_loss: 28068842307584.0000
Epoch 138/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24984128847872.0000 - val_loss: 28003004317696.0000
Epoch 139/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23010245345280.0000 - val_loss: 27933102047232.0000
Epoch 140/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22978395897856.0000 - val_loss: 27862121840640.0000
Epoch 141/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23002506854400.0000 - val_loss: 27790241955840.0000
Epoch 142/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22814404902912.0000 - val_loss: 27716359290880.0000
Epoch 143/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24100779065344.0000 - val_loss: 27641948143616.0000
Epoch 144/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23473493639168.0000 - val_loss: 27564726812672.0000
Epoch 145/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23530276126720.0000 - val_loss: 27486161207296.0000
Epoch 146/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23297211236352.0000 - val_loss: 27405626376192.0000
Epoch 147/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22536817475584.0000 - val_loss: 27320563793920.0000
Epoch 148/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21854104322048.0000 - val_loss: 27235643817984.0000
Epoch 149/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 22966991585280.0000 - val_loss: 27151149563904.0000
Epoch 150/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23682858614784.0000 - val_loss: 27064902090752.0000
Epoch 151/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22737554767872.0000 - val_loss: 26975758450688.0000
Epoch 152/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22112905461760.0000 - val_loss: 26883439722496.0000
Epoch 153/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22201887621120.0000 - val_loss: 26788281450496.0000
Epoch 154/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21735921418240.0000 - val_loss: 26692355620864.0000
Epoch 155/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21862859931648.0000 - val_loss: 26593481195520.0000
Epoch 156/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22017933836288.0000 - val_loss: 26493734354944.0000
Epoch 157/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21788312469504.0000 - val_loss: 26392219615232.0000
Epoch 158/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21389903921152.0000 - val_loss: 26287022276608.0000
Epoch 159/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 21264345333760.0000 - val_loss: 26180933648384.0000
Epoch 160/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 21326238580736.0000 - val_loss: 26072284397568.0000
Epoch 161/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22370093891584.0000 - val_loss: 25961806430208.0000
Epoch 162/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22358477766656.0000 - val_loss: 25850439270400.0000
Epoch 163/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20964490346496.0000 - val_loss: 25734573719552.0000
Epoch 164/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21395578814464.0000 - val_loss: 25615849750528.0000
Epoch 165/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20640891404288.0000 - val_loss: 25497176113152.0000
Epoch 166/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 22423776788480.0000 - val_loss: 25377978187776.0000
Epoch 167/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 20468564230144.0000 - val_loss: 25251962421248.0000
Epoch 168/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20753405706240.0000 - val_loss: 25124342333440.0000
Epoch 169/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20543021514752.0000 - val_loss: 24994704785408.0000
Epoch 170/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20420466049024.0000 - val_loss: 24862064115712.0000
Epoch 171/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19615249858560.0000 - val_loss: 24727695392768.0000
Epoch 172/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 20928895385600.0000 - val_loss: 24593892900864.0000
Epoch 173/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19657392128000.0000 - val_loss: 24453513740288.0000
Epoch 174/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20780591087616.0000 - val_loss: 24314267041792.0000
Epoch 175/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20372946681856.0000 - val_loss: 24171197235200.0000
Epoch 176/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 19123853590528.0000 - val_loss: 24025547931648.0000
Epoch 177/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 19149908606976.0000 - val_loss: 23876274749440.0000
Epoch 178/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20196311957504.0000 - val_loss: 23725128810496.0000
Epoch 179/200
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20270790213632.0000 - val_loss: 23572307247104.0000
Epoch 180/200

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

In [79]:
train_rmse = math.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = math.sqrt(mean_squared_error(y_test, y_test_pred))
train_mse=mean_squared_error(y_train, y_train_pred)
test_mse=mean_squared_error(y_test, y_test_pred)
print(f"Training RMSE: {train_rmse}")
print(f"Testing RMSE: {test_rmse}")
print(f"Training MSE: {train_mse}")
print(f"Testing MSE: {test_mse}")

Training RMSE: 4019740.6617243355
Testing RMSE: 4445677.809014954
Training MSE: 16158314987520.0
Testing MSE: 19764051181568.0

In [73]:
from tensorflow.keras.models import load_model
from tensorflow.keras.losses import mse
loaded_model=load_model('/content/housing_price_model.h5', custom_objects={'mse': mse})
new_data=pd.DataFrame([{
    'area':1500,
    'bedrooms':2,
    'bathrooms':2,
    'stories':2,
    'mainroad':1,
    'guestroom':1,
    'basement':1,
    'hotwaterheating':1,
    'airconditioning':1,
    'parking':2,
    'prefarea':1,
    'furnishingstatus':1
}])

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [74]:
new_data_scaled=scaler.transform(new_data[numerical_features])
prediction = loaded_model.predict(new_data_scaled)
print("Predicted price:", prediction[0, 0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Predicted price: 630572.6